"Required Changes" Branch
300ms/Enumerable-Methods pull request #3
Opened 2019-11-22 19:56 UTC by 300ms

This is feature branch to get a code review for if all requested changes have been made or not.

2019-11-22 20:43 UTC, wathigo requested changes
## Changes Required 

Hi Devs :wave: ,
Great work implementing the [Git Flow](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/).
Let's refer to [Ruby docs](https://ruby-doc.org/core-2.6.5/Enumerable.html) for the correct behaviour of the methods.
Let's fix the issues pointed out in the comments :point_down:  

### After implementing the changes, submit another request for review.

Feel free to reach out via slack for any issue/clarification.

_Happy Coding :computer: 
Reviewed by: **Simon Wathigo**_

2019-11-22 20:43 UTC, wathigo commented on enumerable_methods.rb
>          i += 1
**[REQUIRED]**
* When a class is passed as an argument returns true if all of the collection is a member of such class.
```
Failure/Error: expect(array.my_all?(Integer)).to be array.all?(Integer)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```
* When a Regex is passed as an argument returns true if all of the collection matches the Regex.
```
Failure/Error: expect(words.my_all?(/d/)).to be words.all?(/d/)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```
* When a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern.
```
Failure/Error: expect(array.my_all?(3)).to be array.all?(3)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

2019-11-22 20:43 UTC, wathigo commented on enumerable_methods.rb
>        false
**[REQUIRED]**
* When a class is passed as an argument returns true if at least one of the collection is a member of such class.
```
Failure/Error: expect(array.my_any?(Integer)).to be array.any?(Integer)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```
* When a Regex is passed as an argument returns false if none of the collection matches the Regex.
```
Failure/Error: expect(words.my_any?(/z/)).to be words.any?(/z/)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```
* When a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern.
```
Failure/Error: expect(words.my_any?('cat')).to be words.any?('cat')
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

2019-11-22 20:43 UTC, wathigo commented on enumerable_methods.rb
>        x
**[REQUIRED]**
* When a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern.
```
Failure/Error: expect(words.my_any?('cat')).to be words.any?('cat')
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```
* When a Regex is passed as an argument returns true only if none of the collection matches the Regex.
```
Failure/Error: expect(words.my_none?(/z/)).to be words.none?(/z/)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```
* When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern.
```
Failure/Error: expect(words.my_none?(5)).to be words.none?(5)
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
```

2019-11-22 20:43 UTC, wathigo commented on enumerable_methods.rb
>        x
**[REQUIRED]**
* Counts the number of items in enum that are equal to item if an argument is given.
```
Failure/Error: expect(array.my_count(LOWEST_VALUE)).to eq array.count(LOWEST_VALUE)
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
```

2019-11-22 20:43 UTC, wathigo commented on enumerable_methods.rb
>  # rubocop: enable Metrics/ModuleLength
## my_map
**[REQUIRED]**

* Returns a new array with the results of running block once for every element in enum.
```
Failure/Error: expect(array.my_map(&block)).to eq array.map(&block)
      
      ArgumentError:
        wrong number of arguments (given 0, expected 1)
```
* Returns an Enumerator if no block is given
```
Failure/Error: expect(array.my_map).to be_an(Enumerator)
      
      ArgumentError:
        wrong number of arguments (given 0, expected 1)
```

2019-11-22 20:43 UTC, wathigo commented on enumerable_methods.rb
>        end
**[REQUIRED]**
* Combines all elements of enum by applying a binary operation, specified by a block.
```
Failure/Error: actual = range.my_inject(4) { |prod, n| prod * n }
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
```
* When a symbol is specified combines each element of the collection by applying the symbol as a named method.
```
Failure/Error: expect(array.my_inject(:+)).to eq array.inject(:+)
      
      ArgumentError:
        wrong number of arguments (given 1, expected 0)
```

2019-11-24 15:25 UTC, whiz25 requested changes
## Good job guys :+1: 
You implemented some of the suggested changes. That's good. However, we can not merge this PR yet because some edge cases are still failing. Look at my comments and do your best to implement them then resubmit for another review.

### Martin Afani

2019-11-24 15:27 UTC, whiz25 commented on enumerable_methods.rb
>        end
- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-24 15:27 UTC, whiz25 commented on enumerable_methods.rb
>    end
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-11-24 15:29 UTC, whiz25 commented on enumerable_methods.rb
>    end
- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-24 15:29 UTC, whiz25 commented on enumerable_methods.rb
>  end
- [ ] returns an Enumerator if no block is given

2019-11-24 15:30 UTC, whiz25 commented on enumerable_methods.rb
>    end
- [ ] combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-11-24 18:42 UTC, whiz25 approved these changes
## Nice try
I know have tried your best to implement the changes but I must say all changes haven't been implemented :disappointed:. This review has reached the max number of cycles so it's a :+1: from me.

### Martin Afani

2019-11-25 08:57 UTC, merged